baseURL: https://sarcasticnastik.github.io
languageCode: en-us
title: AmanR
theme: "PaperMod"

enableEmoji: true
enableRobotsTXT: true

staticDir:
  - static

menu:
  main:
    - identifier: Archives
      name: Archives
      url: "/archives/"
      weight: 10
    - identifier: Tags
      name: Tags
      url: "/tags/"
      weight: 20
    - identifier: search
      name: Search
      url: "/search/"
      weight: 30
    # - identifier: Research
    #   name: Research
    #   url: "/research/"
    #   weight: 5
    - identifier: Section
      name: Section
      url: "/section/"
      weight: 25

params:
  env: production
  description: "Portfolio website of Aman Rojjha"
  author: "Aman Rojjha"
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true

  homeInfoParams:
    Title: Hi there! I'm Aman.
    Content: I'm an undergraduate researcher, currently interested in Reinforcement Learning, Deep Learning and Differential Privacy.

  profileMode:
    enabled: true
    title: "Aman Rojjha"
    subtitle: "I'm an undergraduate researcher, currently interested in Reinforcement Learning, Deep Learning and Differential Privacy."
    imageUrl: ""
    # buttons:
    #   - name: Archive
    #     url: "/archives/"
    #   - name: Research
    #     url: "/research/"
    #   - name: Search
    #     url: "/search"
  markup:
    highlight:
      style: monokai
      codeFences: true
      guessSyntax: true
      lineNos: true

  socialIcons:
    - name: Facebook
      url: "https://www.facebook.com/aman.rojjha"
    - name: Github
      url: "https://github.com/SarcasticNastik"

  editPost:
    URL: "https://github.com/SarcasticNastik/SarcasticNastik.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
